/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEarningsRouteImport } from './routes/_app.earnings'
import { Route as AppNetworkRouteImport } from './routes/_app.network'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppVouchersRouteImport } from './routes/_app.vouchers'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AppCheckoutIndexRouteImport } from './routes/_app.checkout.index'
import { Route as AppCheckoutAddressesRouteImport } from './routes/_app.checkout.addresses'
import { Route as AppCheckoutResultRouteImport } from './routes/_app.checkout.result'
import { Route as AppCheckoutVouchersRouteImport } from './routes/_app.checkout.vouchers'
import { Route as AppEarningsIndexRouteImport } from './routes/_app.earnings.index'
import { Route as AppEarningsPairingRouteImport } from './routes/_app.earnings.pairing'
import { Route as AppEarningsRewardsRouteImport } from './routes/_app.earnings.rewards'
import { Route as AppEarningsSponsorRouteImport } from './routes/_app.earnings.sponsor'
import { Route as AppNetworkIndexRouteImport } from './routes/_app.network.index'
import { Route as AppNetworkGenealogyRouteImport } from './routes/_app.network.genealogy'
import { Route as AppNetworkReferralRouteImport } from './routes/_app.network.referral'
import { Route as AppProductsProductIdRouteImport } from './routes/_app.products.$productId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAccountSecurityRouteImport } from './routes/_app.settings.account-security'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppWalletIndexRouteImport } from './routes/_app.wallet.index'
import { Route as AppWalletWithdrawRouteImport } from './routes/_app.wallet.withdraw'
import { Route as AppCheckoutAddressesIndexRouteImport } from './routes/_app.checkout.addresses.index'
import { Route as AppCheckoutAddressesLocationRouteImport } from './routes/_app.checkout.addresses.location'
import { Route as AppCheckoutAddressesNewRouteImport } from './routes/_app.checkout.addresses.new'
import { Route as AppSettingsProfileIndexRouteImport } from './routes/_app.settings.profile.index'
import { Route as AppSettingsProfileBioRouteImport } from './routes/_app.settings.profile.bio'
import { Route as AppSettingsProfileGenderRouteImport } from './routes/_app.settings.profile.gender'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AppCheckoutIndexRoute = AppCheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCheckoutRoute,
} as any)
const AppCheckoutAddressesRoute = AppCheckoutAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppCheckoutRoute,
} as any)
const AppCheckoutResultRoute = AppCheckoutResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppCheckoutRoute,
} as any)
const AppCheckoutVouchersRoute = AppCheckoutVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppCheckoutRoute,
} as any)
const AppEarningsIndexRoute = AppEarningsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEarningsRoute,
} as any)
const AppEarningsPairingRoute = AppEarningsPairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => AppEarningsRoute,
} as any)
const AppEarningsRewardsRoute = AppEarningsRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppEarningsRoute,
} as any)
const AppEarningsSponsorRoute = AppEarningsSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AppEarningsRoute,
} as any)
const AppNetworkIndexRoute = AppNetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNetworkRoute,
} as any)
const AppNetworkGenealogyRoute = AppNetworkGenealogyRouteImport.update({
  id: '/genealogy',
  path: '/genealogy',
  getParentRoute: () => AppNetworkRoute,
} as any)
const AppNetworkReferralRoute = AppNetworkReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppNetworkRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountSecurityRoute =
  AppSettingsAccountSecurityRouteImport.update({
    id: '/account-security',
    path: '/account-security',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWalletRoute,
} as any)
const AppWalletWithdrawRoute = AppWalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppWalletRoute,
} as any)
const AppCheckoutAddressesIndexRoute =
  AppCheckoutAddressesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCheckoutAddressesRoute,
  } as any)
const AppCheckoutAddressesLocationRoute =
  AppCheckoutAddressesLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AppCheckoutAddressesRoute,
  } as any)
const AppCheckoutAddressesNewRoute = AppCheckoutAddressesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCheckoutAddressesRoute,
} as any)
const AppSettingsProfileIndexRoute = AppSettingsProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsProfileRoute,
} as any)
const AppSettingsProfileBioRoute = AppSettingsProfileBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => AppSettingsProfileRoute,
} as any)
const AppSettingsProfileGenderRoute =
  AppSettingsProfileGenderRouteImport.update({
    id: '/gender',
    path: '/gender',
    getParentRoute: () => AppSettingsProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/earnings': typeof AppEarningsRouteWithChildren
  '/network': typeof AppNetworkRouteWithChildren
  '/orders': typeof AppOrdersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/shop': typeof AppShopRoute
  '/vouchers': typeof AppVouchersRoute
  '/wallet': typeof AppWalletRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/checkout/addresses': typeof AppCheckoutAddressesRouteWithChildren
  '/checkout/result': typeof AppCheckoutResultRoute
  '/checkout/vouchers': typeof AppCheckoutVouchersRoute
  '/earnings/pairing': typeof AppEarningsPairingRoute
  '/earnings/rewards': typeof AppEarningsRewardsRoute
  '/earnings/sponsor': typeof AppEarningsSponsorRoute
  '/network/genealogy': typeof AppNetworkGenealogyRoute
  '/network/referral': typeof AppNetworkReferralRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/settings/account-security': typeof AppSettingsAccountSecurityRoute
  '/settings/profile': typeof AppSettingsProfileRouteWithChildren
  '/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/checkout/': typeof AppCheckoutIndexRoute
  '/earnings/': typeof AppEarningsIndexRoute
  '/network/': typeof AppNetworkIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/wallet/': typeof AppWalletIndexRoute
  '/checkout/addresses/location': typeof AppCheckoutAddressesLocationRoute
  '/checkout/addresses/new': typeof AppCheckoutAddressesNewRoute
  '/settings/profile/bio': typeof AppSettingsProfileBioRoute
  '/settings/profile/gender': typeof AppSettingsProfileGenderRoute
  '/checkout/addresses/': typeof AppCheckoutAddressesIndexRoute
  '/settings/profile/': typeof AppSettingsProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/cart': typeof AppCartRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/shop': typeof AppShopRoute
  '/vouchers': typeof AppVouchersRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/checkout/result': typeof AppCheckoutResultRoute
  '/checkout/vouchers': typeof AppCheckoutVouchersRoute
  '/earnings/pairing': typeof AppEarningsPairingRoute
  '/earnings/rewards': typeof AppEarningsRewardsRoute
  '/earnings/sponsor': typeof AppEarningsSponsorRoute
  '/network/genealogy': typeof AppNetworkGenealogyRoute
  '/network/referral': typeof AppNetworkReferralRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/settings/account-security': typeof AppSettingsAccountSecurityRoute
  '/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/checkout': typeof AppCheckoutIndexRoute
  '/earnings': typeof AppEarningsIndexRoute
  '/network': typeof AppNetworkIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/wallet': typeof AppWalletIndexRoute
  '/checkout/addresses/location': typeof AppCheckoutAddressesLocationRoute
  '/checkout/addresses/new': typeof AppCheckoutAddressesNewRoute
  '/settings/profile/bio': typeof AppSettingsProfileBioRoute
  '/settings/profile/gender': typeof AppSettingsProfileGenderRoute
  '/checkout/addresses': typeof AppCheckoutAddressesIndexRoute
  '/settings/profile': typeof AppSettingsProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/cart': typeof AppCartRoute
  '/_app/checkout': typeof AppCheckoutRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/earnings': typeof AppEarningsRouteWithChildren
  '/_app/network': typeof AppNetworkRouteWithChildren
  '/_app/orders': typeof AppOrdersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/shop': typeof AppShopRoute
  '/_app/vouchers': typeof AppVouchersRoute
  '/_app/wallet': typeof AppWalletRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/checkout/addresses': typeof AppCheckoutAddressesRouteWithChildren
  '/_app/checkout/result': typeof AppCheckoutResultRoute
  '/_app/checkout/vouchers': typeof AppCheckoutVouchersRoute
  '/_app/earnings/pairing': typeof AppEarningsPairingRoute
  '/_app/earnings/rewards': typeof AppEarningsRewardsRoute
  '/_app/earnings/sponsor': typeof AppEarningsSponsorRoute
  '/_app/network/genealogy': typeof AppNetworkGenealogyRoute
  '/_app/network/referral': typeof AppNetworkReferralRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/settings/account-security': typeof AppSettingsAccountSecurityRoute
  '/_app/settings/profile': typeof AppSettingsProfileRouteWithChildren
  '/_app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/_app/checkout/': typeof AppCheckoutIndexRoute
  '/_app/earnings/': typeof AppEarningsIndexRoute
  '/_app/network/': typeof AppNetworkIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/wallet/': typeof AppWalletIndexRoute
  '/_app/checkout/addresses/location': typeof AppCheckoutAddressesLocationRoute
  '/_app/checkout/addresses/new': typeof AppCheckoutAddressesNewRoute
  '/_app/settings/profile/bio': typeof AppSettingsProfileBioRoute
  '/_app/settings/profile/gender': typeof AppSettingsProfileGenderRoute
  '/_app/checkout/addresses/': typeof AppCheckoutAddressesIndexRoute
  '/_app/settings/profile/': typeof AppSettingsProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/earnings'
    | '/network'
    | '/orders'
    | '/settings'
    | '/shop'
    | '/vouchers'
    | '/wallet'
    | '/login'
    | '/register'
    | '/checkout/addresses'
    | '/checkout/result'
    | '/checkout/vouchers'
    | '/earnings/pairing'
    | '/earnings/rewards'
    | '/earnings/sponsor'
    | '/network/genealogy'
    | '/network/referral'
    | '/products/$productId'
    | '/settings/account-security'
    | '/settings/profile'
    | '/wallet/withdraw'
    | '/checkout/'
    | '/earnings/'
    | '/network/'
    | '/settings/'
    | '/wallet/'
    | '/checkout/addresses/location'
    | '/checkout/addresses/new'
    | '/settings/profile/bio'
    | '/settings/profile/gender'
    | '/checkout/addresses/'
    | '/settings/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/orders'
    | '/shop'
    | '/vouchers'
    | '/login'
    | '/register'
    | '/checkout/result'
    | '/checkout/vouchers'
    | '/earnings/pairing'
    | '/earnings/rewards'
    | '/earnings/sponsor'
    | '/network/genealogy'
    | '/network/referral'
    | '/products/$productId'
    | '/settings/account-security'
    | '/wallet/withdraw'
    | '/checkout'
    | '/earnings'
    | '/network'
    | '/settings'
    | '/wallet'
    | '/checkout/addresses/location'
    | '/checkout/addresses/new'
    | '/settings/profile/bio'
    | '/settings/profile/gender'
    | '/checkout/addresses'
    | '/settings/profile'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/cart'
    | '/_app/checkout'
    | '/_app/dashboard'
    | '/_app/earnings'
    | '/_app/network'
    | '/_app/orders'
    | '/_app/settings'
    | '/_app/shop'
    | '/_app/vouchers'
    | '/_app/wallet'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/checkout/addresses'
    | '/_app/checkout/result'
    | '/_app/checkout/vouchers'
    | '/_app/earnings/pairing'
    | '/_app/earnings/rewards'
    | '/_app/earnings/sponsor'
    | '/_app/network/genealogy'
    | '/_app/network/referral'
    | '/_app/products/$productId'
    | '/_app/settings/account-security'
    | '/_app/settings/profile'
    | '/_app/wallet/withdraw'
    | '/_app/checkout/'
    | '/_app/earnings/'
    | '/_app/network/'
    | '/_app/settings/'
    | '/_app/wallet/'
    | '/_app/checkout/addresses/location'
    | '/_app/checkout/addresses/new'
    | '/_app/settings/profile/bio'
    | '/_app/settings/profile/gender'
    | '/_app/checkout/addresses/'
    | '/_app/settings/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earnings': {
      id: '/_app/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vouchers': {
      id: '/_app/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/checkout/': {
      id: '/_app/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AppCheckoutIndexRouteImport
      parentRoute: typeof AppCheckoutRoute
    }
    '/_app/checkout/addresses': {
      id: '/_app/checkout/addresses'
      path: '/addresses'
      fullPath: '/checkout/addresses'
      preLoaderRoute: typeof AppCheckoutAddressesRouteImport
      parentRoute: typeof AppCheckoutRoute
    }
    '/_app/checkout/result': {
      id: '/_app/checkout/result'
      path: '/result'
      fullPath: '/checkout/result'
      preLoaderRoute: typeof AppCheckoutResultRouteImport
      parentRoute: typeof AppCheckoutRoute
    }
    '/_app/checkout/vouchers': {
      id: '/_app/checkout/vouchers'
      path: '/vouchers'
      fullPath: '/checkout/vouchers'
      preLoaderRoute: typeof AppCheckoutVouchersRouteImport
      parentRoute: typeof AppCheckoutRoute
    }
    '/_app/earnings/': {
      id: '/_app/earnings/'
      path: '/'
      fullPath: '/earnings/'
      preLoaderRoute: typeof AppEarningsIndexRouteImport
      parentRoute: typeof AppEarningsRoute
    }
    '/_app/earnings/pairing': {
      id: '/_app/earnings/pairing'
      path: '/pairing'
      fullPath: '/earnings/pairing'
      preLoaderRoute: typeof AppEarningsPairingRouteImport
      parentRoute: typeof AppEarningsRoute
    }
    '/_app/earnings/rewards': {
      id: '/_app/earnings/rewards'
      path: '/rewards'
      fullPath: '/earnings/rewards'
      preLoaderRoute: typeof AppEarningsRewardsRouteImport
      parentRoute: typeof AppEarningsRoute
    }
    '/_app/earnings/sponsor': {
      id: '/_app/earnings/sponsor'
      path: '/sponsor'
      fullPath: '/earnings/sponsor'
      preLoaderRoute: typeof AppEarningsSponsorRouteImport
      parentRoute: typeof AppEarningsRoute
    }
    '/_app/network/': {
      id: '/_app/network/'
      path: '/'
      fullPath: '/network/'
      preLoaderRoute: typeof AppNetworkIndexRouteImport
      parentRoute: typeof AppNetworkRoute
    }
    '/_app/network/genealogy': {
      id: '/_app/network/genealogy'
      path: '/genealogy'
      fullPath: '/network/genealogy'
      preLoaderRoute: typeof AppNetworkGenealogyRouteImport
      parentRoute: typeof AppNetworkRoute
    }
    '/_app/network/referral': {
      id: '/_app/network/referral'
      path: '/referral'
      fullPath: '/network/referral'
      preLoaderRoute: typeof AppNetworkReferralRouteImport
      parentRoute: typeof AppNetworkRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account-security': {
      id: '/_app/settings/account-security'
      path: '/account-security'
      fullPath: '/settings/account-security'
      preLoaderRoute: typeof AppSettingsAccountSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/wallet/': {
      id: '/_app/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppWalletRoute
    }
    '/_app/wallet/withdraw': {
      id: '/_app/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof AppWalletWithdrawRouteImport
      parentRoute: typeof AppWalletRoute
    }
    '/_app/checkout/addresses/': {
      id: '/_app/checkout/addresses/'
      path: '/'
      fullPath: '/checkout/addresses/'
      preLoaderRoute: typeof AppCheckoutAddressesIndexRouteImport
      parentRoute: typeof AppCheckoutAddressesRoute
    }
    '/_app/checkout/addresses/location': {
      id: '/_app/checkout/addresses/location'
      path: '/location'
      fullPath: '/checkout/addresses/location'
      preLoaderRoute: typeof AppCheckoutAddressesLocationRouteImport
      parentRoute: typeof AppCheckoutAddressesRoute
    }
    '/_app/checkout/addresses/new': {
      id: '/_app/checkout/addresses/new'
      path: '/new'
      fullPath: '/checkout/addresses/new'
      preLoaderRoute: typeof AppCheckoutAddressesNewRouteImport
      parentRoute: typeof AppCheckoutAddressesRoute
    }
    '/_app/settings/profile/': {
      id: '/_app/settings/profile/'
      path: '/'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof AppSettingsProfileIndexRouteImport
      parentRoute: typeof AppSettingsProfileRoute
    }
    '/_app/settings/profile/bio': {
      id: '/_app/settings/profile/bio'
      path: '/bio'
      fullPath: '/settings/profile/bio'
      preLoaderRoute: typeof AppSettingsProfileBioRouteImport
      parentRoute: typeof AppSettingsProfileRoute
    }
    '/_app/settings/profile/gender': {
      id: '/_app/settings/profile/gender'
      path: '/gender'
      fullPath: '/settings/profile/gender'
      preLoaderRoute: typeof AppSettingsProfileGenderRouteImport
      parentRoute: typeof AppSettingsProfileRoute
    }
  }
}

interface AppCheckoutAddressesRouteChildren {
  AppCheckoutAddressesLocationRoute: typeof AppCheckoutAddressesLocationRoute
  AppCheckoutAddressesNewRoute: typeof AppCheckoutAddressesNewRoute
  AppCheckoutAddressesIndexRoute: typeof AppCheckoutAddressesIndexRoute
}

const AppCheckoutAddressesRouteChildren: AppCheckoutAddressesRouteChildren = {
  AppCheckoutAddressesLocationRoute: AppCheckoutAddressesLocationRoute,
  AppCheckoutAddressesNewRoute: AppCheckoutAddressesNewRoute,
  AppCheckoutAddressesIndexRoute: AppCheckoutAddressesIndexRoute,
}

const AppCheckoutAddressesRouteWithChildren =
  AppCheckoutAddressesRoute._addFileChildren(AppCheckoutAddressesRouteChildren)

interface AppCheckoutRouteChildren {
  AppCheckoutAddressesRoute: typeof AppCheckoutAddressesRouteWithChildren
  AppCheckoutResultRoute: typeof AppCheckoutResultRoute
  AppCheckoutVouchersRoute: typeof AppCheckoutVouchersRoute
  AppCheckoutIndexRoute: typeof AppCheckoutIndexRoute
}

const AppCheckoutRouteChildren: AppCheckoutRouteChildren = {
  AppCheckoutAddressesRoute: AppCheckoutAddressesRouteWithChildren,
  AppCheckoutResultRoute: AppCheckoutResultRoute,
  AppCheckoutVouchersRoute: AppCheckoutVouchersRoute,
  AppCheckoutIndexRoute: AppCheckoutIndexRoute,
}

const AppCheckoutRouteWithChildren = AppCheckoutRoute._addFileChildren(
  AppCheckoutRouteChildren,
)

interface AppEarningsRouteChildren {
  AppEarningsPairingRoute: typeof AppEarningsPairingRoute
  AppEarningsRewardsRoute: typeof AppEarningsRewardsRoute
  AppEarningsSponsorRoute: typeof AppEarningsSponsorRoute
  AppEarningsIndexRoute: typeof AppEarningsIndexRoute
}

const AppEarningsRouteChildren: AppEarningsRouteChildren = {
  AppEarningsPairingRoute: AppEarningsPairingRoute,
  AppEarningsRewardsRoute: AppEarningsRewardsRoute,
  AppEarningsSponsorRoute: AppEarningsSponsorRoute,
  AppEarningsIndexRoute: AppEarningsIndexRoute,
}

const AppEarningsRouteWithChildren = AppEarningsRoute._addFileChildren(
  AppEarningsRouteChildren,
)

interface AppNetworkRouteChildren {
  AppNetworkGenealogyRoute: typeof AppNetworkGenealogyRoute
  AppNetworkReferralRoute: typeof AppNetworkReferralRoute
  AppNetworkIndexRoute: typeof AppNetworkIndexRoute
}

const AppNetworkRouteChildren: AppNetworkRouteChildren = {
  AppNetworkGenealogyRoute: AppNetworkGenealogyRoute,
  AppNetworkReferralRoute: AppNetworkReferralRoute,
  AppNetworkIndexRoute: AppNetworkIndexRoute,
}

const AppNetworkRouteWithChildren = AppNetworkRoute._addFileChildren(
  AppNetworkRouteChildren,
)

interface AppSettingsProfileRouteChildren {
  AppSettingsProfileBioRoute: typeof AppSettingsProfileBioRoute
  AppSettingsProfileGenderRoute: typeof AppSettingsProfileGenderRoute
  AppSettingsProfileIndexRoute: typeof AppSettingsProfileIndexRoute
}

const AppSettingsProfileRouteChildren: AppSettingsProfileRouteChildren = {
  AppSettingsProfileBioRoute: AppSettingsProfileBioRoute,
  AppSettingsProfileGenderRoute: AppSettingsProfileGenderRoute,
  AppSettingsProfileIndexRoute: AppSettingsProfileIndexRoute,
}

const AppSettingsProfileRouteWithChildren =
  AppSettingsProfileRoute._addFileChildren(AppSettingsProfileRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAccountSecurityRoute: typeof AppSettingsAccountSecurityRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRouteWithChildren
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountSecurityRoute: AppSettingsAccountSecurityRoute,
  AppSettingsProfileRoute: AppSettingsProfileRouteWithChildren,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWalletRouteChildren {
  AppWalletWithdrawRoute: typeof AppWalletWithdrawRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
}

const AppWalletRouteChildren: AppWalletRouteChildren = {
  AppWalletWithdrawRoute: AppWalletWithdrawRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
}

const AppWalletRouteWithChildren = AppWalletRoute._addFileChildren(
  AppWalletRouteChildren,
)

interface AppRouteChildren {
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEarningsRoute: typeof AppEarningsRouteWithChildren
  AppNetworkRoute: typeof AppNetworkRouteWithChildren
  AppOrdersRoute: typeof AppOrdersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppShopRoute: typeof AppShopRoute
  AppVouchersRoute: typeof AppVouchersRoute
  AppWalletRoute: typeof AppWalletRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEarningsRoute: AppEarningsRouteWithChildren,
  AppNetworkRoute: AppNetworkRouteWithChildren,
  AppOrdersRoute: AppOrdersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppShopRoute: AppShopRoute,
  AppVouchersRoute: AppVouchersRoute,
  AppWalletRoute: AppWalletRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
